topics:
  - /localization/kinematic_state
  - /localization/acceleration
  - /vehicle/status/steering_status
  - /system/operation_mode/state
  - /control/trajectory_follower/lane_departure_checker_node/debug/deviation/lateral
  - /vehicle/raw_vehicle_cmd_converter/debug/compensated_control_cmd
  - /control/command/control_cmd
  - /control/trajectory_follower/control_cmd
  - /external/selected/control_cmd
  - /control/command/actuation_cmd
  - /pacmod/accel_aux_rpt
  - /pacmod/accel_rpt
  - /pacmod/brake_aux_rpt
  - /pacmod/brake_rpt
