topics:
  - /vehicle/status/velocity_status
  - /control/command/actuation_cmd
  - /sensing/imu/imu_data
  - /vehicle/status/control_mode
  - /control/command/control_cmd
  - /vehicle/status/control_mode
